#!/bin/bash

package=nems-saas-connector

if [[ $EUID == 0 ]]; then
  echo "ERROR: This script must not be run as root" 2>&1
  exit 1
fi

dpkg-deb --build debpack ${package}.deb
mv ${package}.deb /home/admin/repos/apt/nems/
cd /home/admin/repos/apt/nems/
reprepro includedeb saas ${package}.deb
rm ${package}.deb
